export type ViewState = "dashboard" | "chat" | "notes" | "reports";

export interface Message {
  id: string;
  role: "user" | "model";
  content: string;
  timestamp: string;
}

export interface Note {
  id: string;
  title: string;
  content: string;
  createdAt: string;
  category: "work" | "personal" | "ideas" | "urgent" | "health" | "admin" | "school";
  color: string; // Tailwind bg color class
  location?: string; // Optional location metadata
}

export type ReportStatus = "pending" | "progress" | "resolved";

export interface Report {
  id: string;
  title: string;
  department: "IT" | "maintenance" | "security" | "general";
  description: string;
  status: ReportStatus;
  createdAt: string;
  priority?: string;          // Generated by Gemini
  priorityReason?: string;    // Generated by Gemini
  summary?: string;           // Generated by Gemini
  solutions?: string[];       // Generated by Gemini
  location?: string;          // Optional location coordinates/details
  creatorEmail?: string;      // Email of the user who submitted the report
  creatorName?: string;       // Name of the user who submitted the report
  videoUrl?: string;          // Local attachment video object URL or simulated sample video
  photoUrl?: string;          // Local snapped/captured or uploaded photo URL
  isLive?: boolean;           // Whether this ticket represents an active live stream
  liveViewerCount?: number;   // Number of citizens/officials currently watching
  officialStudy?: {
    studiedBy: string;        // Name of the department head / official
    officialPhone: string;    // Callable phone number of the inspector / department head
    investigationNotes: string; // Field notes, assessment, and directives
    studiedAt: string;        // Timestamp under administrative protocol
  };
}
